// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: agentcore.proto

package gogentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentCoreService_Run_FullMethodName    = "/gogent.v1.AgentCoreService/Run"
	AgentCoreService_Stream_FullMethodName = "/gogent.v1.AgentCoreService/Stream"
)

// AgentCoreServiceClient is the client API for AgentCoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentCoreService executes agent logic and streams execution events.
type AgentCoreServiceClient interface {
	// Run executes the agent with the given input and returns the final output.
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error)
	// Stream executes the agent and streams execution events back to the caller.
	Stream(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AgentEvent], error)
}

type agentCoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentCoreServiceClient(cc grpc.ClientConnInterface) AgentCoreServiceClient {
	return &agentCoreServiceClient{cc}
}

func (c *agentCoreServiceClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunResponse)
	err := c.cc.Invoke(ctx, AgentCoreService_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentCoreServiceClient) Stream(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AgentEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentCoreService_ServiceDesc.Streams[0], AgentCoreService_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunRequest, AgentEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentCoreService_StreamClient = grpc.ServerStreamingClient[AgentEvent]

// AgentCoreServiceServer is the server API for AgentCoreService service.
// All implementations must embed UnimplementedAgentCoreServiceServer
// for forward compatibility.
//
// AgentCoreService executes agent logic and streams execution events.
type AgentCoreServiceServer interface {
	// Run executes the agent with the given input and returns the final output.
	Run(context.Context, *RunRequest) (*RunResponse, error)
	// Stream executes the agent and streams execution events back to the caller.
	Stream(*RunRequest, grpc.ServerStreamingServer[AgentEvent]) error
	mustEmbedUnimplementedAgentCoreServiceServer()
}

// UnimplementedAgentCoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentCoreServiceServer struct{}

func (UnimplementedAgentCoreServiceServer) Run(context.Context, *RunRequest) (*RunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedAgentCoreServiceServer) Stream(*RunRequest, grpc.ServerStreamingServer[AgentEvent]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedAgentCoreServiceServer) mustEmbedUnimplementedAgentCoreServiceServer() {}
func (UnimplementedAgentCoreServiceServer) testEmbeddedByValue()                          {}

// UnsafeAgentCoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentCoreServiceServer will
// result in compilation errors.
type UnsafeAgentCoreServiceServer interface {
	mustEmbedUnimplementedAgentCoreServiceServer()
}

func RegisterAgentCoreServiceServer(s grpc.ServiceRegistrar, srv AgentCoreServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentCoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentCoreService_ServiceDesc, srv)
}

func _AgentCoreService_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentCoreServiceServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentCoreService_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentCoreServiceServer).Run(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentCoreService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentCoreServiceServer).Stream(m, &grpc.GenericServerStream[RunRequest, AgentEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentCoreService_StreamServer = grpc.ServerStreamingServer[AgentEvent]

// AgentCoreService_ServiceDesc is the grpc.ServiceDesc for AgentCoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentCoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gogent.v1.AgentCoreService",
	HandlerType: (*AgentCoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _AgentCoreService_Run_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _AgentCoreService_Stream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agentcore.proto",
}
