// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: agentcore.proto

package gogentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventType enumerates the lifecycle events emitted during agent execution.
type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	EventType_EVENT_TYPE_BEFORE_RUN  EventType = 1
	EventType_EVENT_TYPE_AFTER_RUN   EventType = 2
	EventType_EVENT_TYPE_BEFORE_TOOL EventType = 3
	EventType_EVENT_TYPE_AFTER_TOOL  EventType = 4
	EventType_EVENT_TYPE_BEFORE_LLM  EventType = 5
	EventType_EVENT_TYPE_AFTER_LLM   EventType = 6
	EventType_EVENT_TYPE_ERROR       EventType = 7
	EventType_EVENT_TYPE_STREAMING   EventType = 8
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_BEFORE_RUN",
		2: "EVENT_TYPE_AFTER_RUN",
		3: "EVENT_TYPE_BEFORE_TOOL",
		4: "EVENT_TYPE_AFTER_TOOL",
		5: "EVENT_TYPE_BEFORE_LLM",
		6: "EVENT_TYPE_AFTER_LLM",
		7: "EVENT_TYPE_ERROR",
		8: "EVENT_TYPE_STREAMING",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED": 0,
		"EVENT_TYPE_BEFORE_RUN":  1,
		"EVENT_TYPE_AFTER_RUN":   2,
		"EVENT_TYPE_BEFORE_TOOL": 3,
		"EVENT_TYPE_AFTER_TOOL":  4,
		"EVENT_TYPE_BEFORE_LLM":  5,
		"EVENT_TYPE_AFTER_LLM":   6,
		"EVENT_TYPE_ERROR":       7,
		"EVENT_TYPE_STREAMING":   8,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_agentcore_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_agentcore_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_agentcore_proto_rawDescGZIP(), []int{0}
}

// Message represents a single chat message.
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Tools         []*AgentToolInfo       `protobuf:"bytes,3,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_agentcore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_agentcore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_agentcore_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetTools() []*AgentToolInfo {
	if x != nil {
		return x.Tools
	}
	return nil
}

// AgentToolInfo describes a tool available to the agent.
type AgentToolInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Parameters    *structpb.Struct       `protobuf:"bytes,3,opt,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentToolInfo) Reset() {
	*x = AgentToolInfo{}
	mi := &file_agentcore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentToolInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentToolInfo) ProtoMessage() {}

func (x *AgentToolInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agentcore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentToolInfo.ProtoReflect.Descriptor instead.
func (*AgentToolInfo) Descriptor() ([]byte, []int) {
	return file_agentcore_proto_rawDescGZIP(), []int{1}
}

func (x *AgentToolInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentToolInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AgentToolInfo) GetParameters() *structpb.Struct {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// Action records a tool invocation requested or performed by the agent.
type Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolName      string                 `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Params        *structpb.Struct       `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	Result        *structpb.Value        `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_agentcore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_agentcore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_agentcore_proto_rawDescGZIP(), []int{2}
}

func (x *Action) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *Action) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Action) GetResult() *structpb.Value {
	if x != nil {
		return x.Result
	}
	return nil
}

// AgentInput is the input to an agent execution.
type AgentInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Context       *structpb.Struct       `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInput) Reset() {
	*x = AgentInput{}
	mi := &file_agentcore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInput) ProtoMessage() {}

func (x *AgentInput) ProtoReflect() protoreflect.Message {
	mi := &file_agentcore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInput.ProtoReflect.Descriptor instead.
func (*AgentInput) Descriptor() ([]byte, []int) {
	return file_agentcore_proto_rawDescGZIP(), []int{3}
}

func (x *AgentInput) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *AgentInput) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

// AgentOutput is the result of an agent execution.
type AgentOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Message               `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Actions       []*Action              `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentOutput) Reset() {
	*x = AgentOutput{}
	mi := &file_agentcore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentOutput) ProtoMessage() {}

func (x *AgentOutput) ProtoReflect() protoreflect.Message {
	mi := &file_agentcore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentOutput.ProtoReflect.Descriptor instead.
func (*AgentOutput) Descriptor() ([]byte, []int) {
	return file_agentcore_proto_rawDescGZIP(), []int{4}
}

func (x *AgentOutput) GetResponse() *Message {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *AgentOutput) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *AgentOutput) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         *AgentInput            `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_agentcore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentcore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_agentcore_proto_rawDescGZIP(), []int{5}
}

func (x *RunRequest) GetInput() *AgentInput {
	if x != nil {
		return x.Input
	}
	return nil
}

type RunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        *AgentOutput           `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_agentcore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentcore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_agentcore_proto_rawDescGZIP(), []int{6}
}

func (x *RunResponse) GetOutput() *AgentOutput {
	if x != nil {
		return x.Output
	}
	return nil
}

// AgentEvent is a lifecycle event emitted during agent execution.
type AgentEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=gogent.v1.EventType" json:"type,omitempty"`
	Payload       *structpb.Value        `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	mi := &file_agentcore_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agentcore_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_agentcore_proto_rawDescGZIP(), []int{7}
}

func (x *AgentEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *AgentEvent) GetPayload() *structpb.Value {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_agentcore_proto protoreflect.FileDescriptor

const file_agentcore_proto_rawDesc = "" +
	"\n" +
	"\x0fagentcore.proto\x12\tgogent.v1\x1a\x1cgoogle/protobuf/struct.proto\"g\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12.\n" +
	"\x05tools\x18\x03 \x03(\v2\x18.gogent.v1.AgentToolInfoR\x05tools\"~\n" +
	"\rAgentToolInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x127\n" +
	"\n" +
	"parameters\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"parameters\"\x86\x01\n" +
	"\x06Action\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12/\n" +
	"\x06params\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06params\x12.\n" +
	"\x06result\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\x06result\"o\n" +
	"\n" +
	"AgentInput\x12.\n" +
	"\bmessages\x18\x01 \x03(\v2\x12.gogent.v1.MessageR\bmessages\x121\n" +
	"\acontext\x18\x02 \x01(\v2\x17.google.protobuf.StructR\acontext\"\x9f\x01\n" +
	"\vAgentOutput\x12.\n" +
	"\bresponse\x18\x01 \x01(\v2\x12.gogent.v1.MessageR\bresponse\x12+\n" +
	"\aactions\x18\x02 \x03(\v2\x11.gogent.v1.ActionR\aactions\x123\n" +
	"\bmetadata\x18\x03 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"9\n" +
	"\n" +
	"RunRequest\x12+\n" +
	"\x05input\x18\x01 \x01(\v2\x15.gogent.v1.AgentInputR\x05input\"=\n" +
	"\vRunResponse\x12.\n" +
	"\x06output\x18\x01 \x01(\v2\x16.gogent.v1.AgentOutputR\x06output\"~\n" +
	"\n" +
	"AgentEvent\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.gogent.v1.EventTypeR\x04type\x120\n" +
	"\apayload\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\apayload\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error*\xf8\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15EVENT_TYPE_BEFORE_RUN\x10\x01\x12\x18\n" +
	"\x14EVENT_TYPE_AFTER_RUN\x10\x02\x12\x1a\n" +
	"\x16EVENT_TYPE_BEFORE_TOOL\x10\x03\x12\x19\n" +
	"\x15EVENT_TYPE_AFTER_TOOL\x10\x04\x12\x19\n" +
	"\x15EVENT_TYPE_BEFORE_LLM\x10\x05\x12\x18\n" +
	"\x14EVENT_TYPE_AFTER_LLM\x10\x06\x12\x14\n" +
	"\x10EVENT_TYPE_ERROR\x10\a\x12\x18\n" +
	"\x14EVENT_TYPE_STREAMING\x10\b2\x82\x01\n" +
	"\x10AgentCoreService\x124\n" +
	"\x03Run\x12\x15.gogent.v1.RunRequest\x1a\x16.gogent.v1.RunResponse\x128\n" +
	"\x06Stream\x12\x15.gogent.v1.RunRequest\x1a\x15.gogent.v1.AgentEvent0\x01B\xa6\x01\n" +
	"\rcom.gogent.v1B\x0eAgentcoreProtoP\x01Z@github.com/tltre/gogent/internal/grpctransport/gogentv1;gogentv1\xa2\x02\x03GXX\xaa\x02\tGogent.V1\xca\x02\tGogent\\V1\xe2\x02\x15Gogent\\V1\\GPBMetadata\xea\x02\n" +
	"Gogent::V1b\x06proto3"

var (
	file_agentcore_proto_rawDescOnce sync.Once
	file_agentcore_proto_rawDescData []byte
)

func file_agentcore_proto_rawDescGZIP() []byte {
	file_agentcore_proto_rawDescOnce.Do(func() {
		file_agentcore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agentcore_proto_rawDesc), len(file_agentcore_proto_rawDesc)))
	})
	return file_agentcore_proto_rawDescData
}

var file_agentcore_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agentcore_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_agentcore_proto_goTypes = []any{
	(EventType)(0),          // 0: gogent.v1.EventType
	(*Message)(nil),         // 1: gogent.v1.Message
	(*AgentToolInfo)(nil),   // 2: gogent.v1.AgentToolInfo
	(*Action)(nil),          // 3: gogent.v1.Action
	(*AgentInput)(nil),      // 4: gogent.v1.AgentInput
	(*AgentOutput)(nil),     // 5: gogent.v1.AgentOutput
	(*RunRequest)(nil),      // 6: gogent.v1.RunRequest
	(*RunResponse)(nil),     // 7: gogent.v1.RunResponse
	(*AgentEvent)(nil),      // 8: gogent.v1.AgentEvent
	(*structpb.Struct)(nil), // 9: google.protobuf.Struct
	(*structpb.Value)(nil),  // 10: google.protobuf.Value
}
var file_agentcore_proto_depIdxs = []int32{
	2,  // 0: gogent.v1.Message.tools:type_name -> gogent.v1.AgentToolInfo
	9,  // 1: gogent.v1.AgentToolInfo.parameters:type_name -> google.protobuf.Struct
	9,  // 2: gogent.v1.Action.params:type_name -> google.protobuf.Struct
	10, // 3: gogent.v1.Action.result:type_name -> google.protobuf.Value
	1,  // 4: gogent.v1.AgentInput.messages:type_name -> gogent.v1.Message
	9,  // 5: gogent.v1.AgentInput.context:type_name -> google.protobuf.Struct
	1,  // 6: gogent.v1.AgentOutput.response:type_name -> gogent.v1.Message
	3,  // 7: gogent.v1.AgentOutput.actions:type_name -> gogent.v1.Action
	9,  // 8: gogent.v1.AgentOutput.metadata:type_name -> google.protobuf.Struct
	4,  // 9: gogent.v1.RunRequest.input:type_name -> gogent.v1.AgentInput
	5,  // 10: gogent.v1.RunResponse.output:type_name -> gogent.v1.AgentOutput
	0,  // 11: gogent.v1.AgentEvent.type:type_name -> gogent.v1.EventType
	10, // 12: gogent.v1.AgentEvent.payload:type_name -> google.protobuf.Value
	6,  // 13: gogent.v1.AgentCoreService.Run:input_type -> gogent.v1.RunRequest
	6,  // 14: gogent.v1.AgentCoreService.Stream:input_type -> gogent.v1.RunRequest
	7,  // 15: gogent.v1.AgentCoreService.Run:output_type -> gogent.v1.RunResponse
	8,  // 16: gogent.v1.AgentCoreService.Stream:output_type -> gogent.v1.AgentEvent
	15, // [15:17] is the sub-list for method output_type
	13, // [13:15] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_agentcore_proto_init() }
func file_agentcore_proto_init() {
	if File_agentcore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agentcore_proto_rawDesc), len(file_agentcore_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agentcore_proto_goTypes,
		DependencyIndexes: file_agentcore_proto_depIdxs,
		EnumInfos:         file_agentcore_proto_enumTypes,
		MessageInfos:      file_agentcore_proto_msgTypes,
	}.Build()
	File_agentcore_proto = out.File
	file_agentcore_proto_goTypes = nil
	file_agentcore_proto_depIdxs = nil
}
