// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: contextmanager.proto

package gogentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ContextMessage represents a single message in a conversation.
type ContextMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Extra         *structpb.Struct       `protobuf:"bytes,4,opt,name=extra,proto3" json:"extra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextMessage) Reset() {
	*x = ContextMessage{}
	mi := &file_contextmanager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextMessage) ProtoMessage() {}

func (x *ContextMessage) ProtoReflect() protoreflect.Message {
	mi := &file_contextmanager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextMessage.ProtoReflect.Descriptor instead.
func (*ContextMessage) Descriptor() ([]byte, []int) {
	return file_contextmanager_proto_rawDescGZIP(), []int{0}
}

func (x *ContextMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ContextMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ContextMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ContextMessage) GetExtra() *structpb.Struct {
	if x != nil {
		return x.Extra
	}
	return nil
}

// Summary holds a condensed version of the conversation.
type Summary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	KeyPoints     []string               `protobuf:"bytes,2,rep,name=key_points,json=keyPoints,proto3" json:"key_points,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Summary) Reset() {
	*x = Summary{}
	mi := &file_contextmanager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Summary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Summary) ProtoMessage() {}

func (x *Summary) ProtoReflect() protoreflect.Message {
	mi := &file_contextmanager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Summary.ProtoReflect.Descriptor instead.
func (*Summary) Descriptor() ([]byte, []int) {
	return file_contextmanager_proto_rawDescGZIP(), []int{1}
}

func (x *Summary) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Summary) GetKeyPoints() []string {
	if x != nil {
		return x.KeyPoints
	}
	return nil
}

func (x *Summary) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type NewSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewSessionRequest) Reset() {
	*x = NewSessionRequest{}
	mi := &file_contextmanager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewSessionRequest) ProtoMessage() {}

func (x *NewSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contextmanager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewSessionRequest.ProtoReflect.Descriptor instead.
func (*NewSessionRequest) Descriptor() ([]byte, []int) {
	return file_contextmanager_proto_rawDescGZIP(), []int{2}
}

type NewSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewSessionResponse) Reset() {
	*x = NewSessionResponse{}
	mi := &file_contextmanager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewSessionResponse) ProtoMessage() {}

func (x *NewSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contextmanager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewSessionResponse.ProtoReflect.Descriptor instead.
func (*NewSessionResponse) Descriptor() ([]byte, []int) {
	return file_contextmanager_proto_rawDescGZIP(), []int{3}
}

func (x *NewSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type AddMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message       *ContextMessage        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMessageRequest) Reset() {
	*x = AddMessageRequest{}
	mi := &file_contextmanager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMessageRequest) ProtoMessage() {}

func (x *AddMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contextmanager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMessageRequest.ProtoReflect.Descriptor instead.
func (*AddMessageRequest) Descriptor() ([]byte, []int) {
	return file_contextmanager_proto_rawDescGZIP(), []int{4}
}

func (x *AddMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AddMessageRequest) GetMessage() *ContextMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type AddMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMessageResponse) Reset() {
	*x = AddMessageResponse{}
	mi := &file_contextmanager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMessageResponse) ProtoMessage() {}

func (x *AddMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contextmanager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMessageResponse.ProtoReflect.Descriptor instead.
func (*AddMessageResponse) Descriptor() ([]byte, []int) {
	return file_contextmanager_proto_rawDescGZIP(), []int{5}
}

type GetMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_contextmanager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contextmanager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_contextmanager_proto_rawDescGZIP(), []int{6}
}

func (x *GetMessagesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ContextMessage      `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_contextmanager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contextmanager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_contextmanager_proto_rawDescGZIP(), []int{7}
}

func (x *GetMessagesResponse) GetMessages() []*ContextMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type GetSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSummaryRequest) Reset() {
	*x = GetSummaryRequest{}
	mi := &file_contextmanager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSummaryRequest) ProtoMessage() {}

func (x *GetSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contextmanager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetSummaryRequest) Descriptor() ([]byte, []int) {
	return file_contextmanager_proto_rawDescGZIP(), []int{8}
}

func (x *GetSummaryRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       *Summary               `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSummaryResponse) Reset() {
	*x = GetSummaryResponse{}
	mi := &file_contextmanager_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSummaryResponse) ProtoMessage() {}

func (x *GetSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contextmanager_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetSummaryResponse) Descriptor() ([]byte, []int) {
	return file_contextmanager_proto_rawDescGZIP(), []int{9}
}

func (x *GetSummaryResponse) GetSummary() *Summary {
	if x != nil {
		return x.Summary
	}
	return nil
}

type BuildSystemPromptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildSystemPromptRequest) Reset() {
	*x = BuildSystemPromptRequest{}
	mi := &file_contextmanager_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildSystemPromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildSystemPromptRequest) ProtoMessage() {}

func (x *BuildSystemPromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contextmanager_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildSystemPromptRequest.ProtoReflect.Descriptor instead.
func (*BuildSystemPromptRequest) Descriptor() ([]byte, []int) {
	return file_contextmanager_proto_rawDescGZIP(), []int{10}
}

func (x *BuildSystemPromptRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type BuildSystemPromptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SystemPrompt  string                 `protobuf:"bytes,1,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildSystemPromptResponse) Reset() {
	*x = BuildSystemPromptResponse{}
	mi := &file_contextmanager_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildSystemPromptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildSystemPromptResponse) ProtoMessage() {}

func (x *BuildSystemPromptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contextmanager_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildSystemPromptResponse.ProtoReflect.Descriptor instead.
func (*BuildSystemPromptResponse) Descriptor() ([]byte, []int) {
	return file_contextmanager_proto_rawDescGZIP(), []int{11}
}

func (x *BuildSystemPromptResponse) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

type ContextClearRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextClearRequest) Reset() {
	*x = ContextClearRequest{}
	mi := &file_contextmanager_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextClearRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextClearRequest) ProtoMessage() {}

func (x *ContextClearRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contextmanager_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextClearRequest.ProtoReflect.Descriptor instead.
func (*ContextClearRequest) Descriptor() ([]byte, []int) {
	return file_contextmanager_proto_rawDescGZIP(), []int{12}
}

func (x *ContextClearRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ContextClearResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextClearResponse) Reset() {
	*x = ContextClearResponse{}
	mi := &file_contextmanager_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextClearResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextClearResponse) ProtoMessage() {}

func (x *ContextClearResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contextmanager_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextClearResponse.ProtoReflect.Descriptor instead.
func (*ContextClearResponse) Descriptor() ([]byte, []int) {
	return file_contextmanager_proto_rawDescGZIP(), []int{13}
}

type DeleteSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_contextmanager_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contextmanager_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_contextmanager_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DeleteSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionResponse) Reset() {
	*x = DeleteSessionResponse{}
	mi := &file_contextmanager_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionResponse) ProtoMessage() {}

func (x *DeleteSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contextmanager_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSessionResponse) Descriptor() ([]byte, []int) {
	return file_contextmanager_proto_rawDescGZIP(), []int{15}
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_contextmanager_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contextmanager_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_contextmanager_proto_rawDescGZIP(), []int{16}
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionIds    []string               `protobuf:"bytes,1,rep,name=session_ids,json=sessionIds,proto3" json:"session_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_contextmanager_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contextmanager_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_contextmanager_proto_rawDescGZIP(), []int{17}
}

func (x *ListSessionsResponse) GetSessionIds() []string {
	if x != nil {
		return x.SessionIds
	}
	return nil
}

var File_contextmanager_proto protoreflect.FileDescriptor

const file_contextmanager_proto_rawDesc = "" +
	"\n" +
	"\x14contextmanager.proto\x12\tgogent.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa7\x01\n" +
	"\x0eContextMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12-\n" +
	"\x05extra\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x05extra\"|\n" +
	"\aSummary\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"key_points\x18\x02 \x03(\tR\tkeyPoints\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x13\n" +
	"\x11NewSessionRequest\"3\n" +
	"\x12NewSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"g\n" +
	"\x11AddMessageRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x123\n" +
	"\amessage\x18\x02 \x01(\v2\x19.gogent.v1.ContextMessageR\amessage\"\x14\n" +
	"\x12AddMessageResponse\"3\n" +
	"\x12GetMessagesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"L\n" +
	"\x13GetMessagesResponse\x125\n" +
	"\bmessages\x18\x01 \x03(\v2\x19.gogent.v1.ContextMessageR\bmessages\"2\n" +
	"\x11GetSummaryRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"B\n" +
	"\x12GetSummaryResponse\x12,\n" +
	"\asummary\x18\x01 \x01(\v2\x12.gogent.v1.SummaryR\asummary\"9\n" +
	"\x18BuildSystemPromptRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"@\n" +
	"\x19BuildSystemPromptResponse\x12#\n" +
	"\rsystem_prompt\x18\x01 \x01(\tR\fsystemPrompt\"4\n" +
	"\x13ContextClearRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x16\n" +
	"\x14ContextClearResponse\"5\n" +
	"\x14DeleteSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x17\n" +
	"\x15DeleteSessionResponse\"\x15\n" +
	"\x13ListSessionsRequest\"7\n" +
	"\x14ListSessionsResponse\x12\x1f\n" +
	"\vsession_ids\x18\x01 \x03(\tR\n" +
	"sessionIds2\x95\x05\n" +
	"\x15ContextManagerService\x12I\n" +
	"\n" +
	"NewSession\x12\x1c.gogent.v1.NewSessionRequest\x1a\x1d.gogent.v1.NewSessionResponse\x12I\n" +
	"\n" +
	"AddMessage\x12\x1c.gogent.v1.AddMessageRequest\x1a\x1d.gogent.v1.AddMessageResponse\x12L\n" +
	"\vGetMessages\x12\x1d.gogent.v1.GetMessagesRequest\x1a\x1e.gogent.v1.GetMessagesResponse\x12I\n" +
	"\n" +
	"GetSummary\x12\x1c.gogent.v1.GetSummaryRequest\x1a\x1d.gogent.v1.GetSummaryResponse\x12^\n" +
	"\x11BuildSystemPrompt\x12#.gogent.v1.BuildSystemPromptRequest\x1a$.gogent.v1.BuildSystemPromptResponse\x12H\n" +
	"\x05Clear\x12\x1e.gogent.v1.ContextClearRequest\x1a\x1f.gogent.v1.ContextClearResponse\x12R\n" +
	"\rDeleteSession\x12\x1f.gogent.v1.DeleteSessionRequest\x1a .gogent.v1.DeleteSessionResponse\x12O\n" +
	"\fListSessions\x12\x1e.gogent.v1.ListSessionsRequest\x1a\x1f.gogent.v1.ListSessionsResponseB\xab\x01\n" +
	"\rcom.gogent.v1B\x13ContextmanagerProtoP\x01Z@github.com/tltre/gogent/internal/grpctransport/gogentv1;gogentv1\xa2\x02\x03GXX\xaa\x02\tGogent.V1\xca\x02\tGogent\\V1\xe2\x02\x15Gogent\\V1\\GPBMetadata\xea\x02\n" +
	"Gogent::V1b\x06proto3"

var (
	file_contextmanager_proto_rawDescOnce sync.Once
	file_contextmanager_proto_rawDescData []byte
)

func file_contextmanager_proto_rawDescGZIP() []byte {
	file_contextmanager_proto_rawDescOnce.Do(func() {
		file_contextmanager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contextmanager_proto_rawDesc), len(file_contextmanager_proto_rawDesc)))
	})
	return file_contextmanager_proto_rawDescData
}

var file_contextmanager_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_contextmanager_proto_goTypes = []any{
	(*ContextMessage)(nil),            // 0: gogent.v1.ContextMessage
	(*Summary)(nil),                   // 1: gogent.v1.Summary
	(*NewSessionRequest)(nil),         // 2: gogent.v1.NewSessionRequest
	(*NewSessionResponse)(nil),        // 3: gogent.v1.NewSessionResponse
	(*AddMessageRequest)(nil),         // 4: gogent.v1.AddMessageRequest
	(*AddMessageResponse)(nil),        // 5: gogent.v1.AddMessageResponse
	(*GetMessagesRequest)(nil),        // 6: gogent.v1.GetMessagesRequest
	(*GetMessagesResponse)(nil),       // 7: gogent.v1.GetMessagesResponse
	(*GetSummaryRequest)(nil),         // 8: gogent.v1.GetSummaryRequest
	(*GetSummaryResponse)(nil),        // 9: gogent.v1.GetSummaryResponse
	(*BuildSystemPromptRequest)(nil),  // 10: gogent.v1.BuildSystemPromptRequest
	(*BuildSystemPromptResponse)(nil), // 11: gogent.v1.BuildSystemPromptResponse
	(*ContextClearRequest)(nil),       // 12: gogent.v1.ContextClearRequest
	(*ContextClearResponse)(nil),      // 13: gogent.v1.ContextClearResponse
	(*DeleteSessionRequest)(nil),      // 14: gogent.v1.DeleteSessionRequest
	(*DeleteSessionResponse)(nil),     // 15: gogent.v1.DeleteSessionResponse
	(*ListSessionsRequest)(nil),       // 16: gogent.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),      // 17: gogent.v1.ListSessionsResponse
	(*timestamppb.Timestamp)(nil),     // 18: google.protobuf.Timestamp
	(*structpb.Struct)(nil),           // 19: google.protobuf.Struct
}
var file_contextmanager_proto_depIdxs = []int32{
	18, // 0: gogent.v1.ContextMessage.timestamp:type_name -> google.protobuf.Timestamp
	19, // 1: gogent.v1.ContextMessage.extra:type_name -> google.protobuf.Struct
	18, // 2: gogent.v1.Summary.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 3: gogent.v1.AddMessageRequest.message:type_name -> gogent.v1.ContextMessage
	0,  // 4: gogent.v1.GetMessagesResponse.messages:type_name -> gogent.v1.ContextMessage
	1,  // 5: gogent.v1.GetSummaryResponse.summary:type_name -> gogent.v1.Summary
	2,  // 6: gogent.v1.ContextManagerService.NewSession:input_type -> gogent.v1.NewSessionRequest
	4,  // 7: gogent.v1.ContextManagerService.AddMessage:input_type -> gogent.v1.AddMessageRequest
	6,  // 8: gogent.v1.ContextManagerService.GetMessages:input_type -> gogent.v1.GetMessagesRequest
	8,  // 9: gogent.v1.ContextManagerService.GetSummary:input_type -> gogent.v1.GetSummaryRequest
	10, // 10: gogent.v1.ContextManagerService.BuildSystemPrompt:input_type -> gogent.v1.BuildSystemPromptRequest
	12, // 11: gogent.v1.ContextManagerService.Clear:input_type -> gogent.v1.ContextClearRequest
	14, // 12: gogent.v1.ContextManagerService.DeleteSession:input_type -> gogent.v1.DeleteSessionRequest
	16, // 13: gogent.v1.ContextManagerService.ListSessions:input_type -> gogent.v1.ListSessionsRequest
	3,  // 14: gogent.v1.ContextManagerService.NewSession:output_type -> gogent.v1.NewSessionResponse
	5,  // 15: gogent.v1.ContextManagerService.AddMessage:output_type -> gogent.v1.AddMessageResponse
	7,  // 16: gogent.v1.ContextManagerService.GetMessages:output_type -> gogent.v1.GetMessagesResponse
	9,  // 17: gogent.v1.ContextManagerService.GetSummary:output_type -> gogent.v1.GetSummaryResponse
	11, // 18: gogent.v1.ContextManagerService.BuildSystemPrompt:output_type -> gogent.v1.BuildSystemPromptResponse
	13, // 19: gogent.v1.ContextManagerService.Clear:output_type -> gogent.v1.ContextClearResponse
	15, // 20: gogent.v1.ContextManagerService.DeleteSession:output_type -> gogent.v1.DeleteSessionResponse
	17, // 21: gogent.v1.ContextManagerService.ListSessions:output_type -> gogent.v1.ListSessionsResponse
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_contextmanager_proto_init() }
func file_contextmanager_proto_init() {
	if File_contextmanager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contextmanager_proto_rawDesc), len(file_contextmanager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contextmanager_proto_goTypes,
		DependencyIndexes: file_contextmanager_proto_depIdxs,
		MessageInfos:      file_contextmanager_proto_msgTypes,
	}.Build()
	File_contextmanager_proto = out.File
	file_contextmanager_proto_goTypes = nil
	file_contextmanager_proto_depIdxs = nil
}
