// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: contextmanager.proto

package gogentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContextManagerService_NewSession_FullMethodName        = "/gogent.v1.ContextManagerService/NewSession"
	ContextManagerService_AddMessage_FullMethodName        = "/gogent.v1.ContextManagerService/AddMessage"
	ContextManagerService_GetMessages_FullMethodName       = "/gogent.v1.ContextManagerService/GetMessages"
	ContextManagerService_GetSummary_FullMethodName        = "/gogent.v1.ContextManagerService/GetSummary"
	ContextManagerService_BuildSystemPrompt_FullMethodName = "/gogent.v1.ContextManagerService/BuildSystemPrompt"
	ContextManagerService_Clear_FullMethodName             = "/gogent.v1.ContextManagerService/Clear"
	ContextManagerService_DeleteSession_FullMethodName     = "/gogent.v1.ContextManagerService/DeleteSession"
	ContextManagerService_ListSessions_FullMethodName      = "/gogent.v1.ContextManagerService/ListSessions"
)

// ContextManagerServiceClient is the client API for ContextManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ContextManagerService manages conversational context and sessions.
type ContextManagerServiceClient interface {
	// NewSession creates a new conversation session.
	NewSession(ctx context.Context, in *NewSessionRequest, opts ...grpc.CallOption) (*NewSessionResponse, error)
	// AddMessage appends a message to the session history.
	AddMessage(ctx context.Context, in *AddMessageRequest, opts ...grpc.CallOption) (*AddMessageResponse, error)
	// GetMessages retrieves the full message history for a session.
	GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error)
	// GetSummary returns the current conversation summary.
	GetSummary(ctx context.Context, in *GetSummaryRequest, opts ...grpc.CallOption) (*GetSummaryResponse, error)
	// BuildSystemPrompt constructs a system prompt from history and summary.
	BuildSystemPrompt(ctx context.Context, in *BuildSystemPromptRequest, opts ...grpc.CallOption) (*BuildSystemPromptResponse, error)
	// Clear removes all messages from a session while keeping the session alive.
	Clear(ctx context.Context, in *ContextClearRequest, opts ...grpc.CallOption) (*ContextClearResponse, error)
	// DeleteSession permanently removes a session.
	DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error)
	// ListSessions returns all active session IDs.
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
}

type contextManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContextManagerServiceClient(cc grpc.ClientConnInterface) ContextManagerServiceClient {
	return &contextManagerServiceClient{cc}
}

func (c *contextManagerServiceClient) NewSession(ctx context.Context, in *NewSessionRequest, opts ...grpc.CallOption) (*NewSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewSessionResponse)
	err := c.cc.Invoke(ctx, ContextManagerService_NewSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextManagerServiceClient) AddMessage(ctx context.Context, in *AddMessageRequest, opts ...grpc.CallOption) (*AddMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddMessageResponse)
	err := c.cc.Invoke(ctx, ContextManagerService_AddMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextManagerServiceClient) GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessagesResponse)
	err := c.cc.Invoke(ctx, ContextManagerService_GetMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextManagerServiceClient) GetSummary(ctx context.Context, in *GetSummaryRequest, opts ...grpc.CallOption) (*GetSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSummaryResponse)
	err := c.cc.Invoke(ctx, ContextManagerService_GetSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextManagerServiceClient) BuildSystemPrompt(ctx context.Context, in *BuildSystemPromptRequest, opts ...grpc.CallOption) (*BuildSystemPromptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildSystemPromptResponse)
	err := c.cc.Invoke(ctx, ContextManagerService_BuildSystemPrompt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextManagerServiceClient) Clear(ctx context.Context, in *ContextClearRequest, opts ...grpc.CallOption) (*ContextClearResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContextClearResponse)
	err := c.cc.Invoke(ctx, ContextManagerService_Clear_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextManagerServiceClient) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSessionResponse)
	err := c.cc.Invoke(ctx, ContextManagerService_DeleteSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextManagerServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, ContextManagerService_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContextManagerServiceServer is the server API for ContextManagerService service.
// All implementations must embed UnimplementedContextManagerServiceServer
// for forward compatibility.
//
// ContextManagerService manages conversational context and sessions.
type ContextManagerServiceServer interface {
	// NewSession creates a new conversation session.
	NewSession(context.Context, *NewSessionRequest) (*NewSessionResponse, error)
	// AddMessage appends a message to the session history.
	AddMessage(context.Context, *AddMessageRequest) (*AddMessageResponse, error)
	// GetMessages retrieves the full message history for a session.
	GetMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error)
	// GetSummary returns the current conversation summary.
	GetSummary(context.Context, *GetSummaryRequest) (*GetSummaryResponse, error)
	// BuildSystemPrompt constructs a system prompt from history and summary.
	BuildSystemPrompt(context.Context, *BuildSystemPromptRequest) (*BuildSystemPromptResponse, error)
	// Clear removes all messages from a session while keeping the session alive.
	Clear(context.Context, *ContextClearRequest) (*ContextClearResponse, error)
	// DeleteSession permanently removes a session.
	DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error)
	// ListSessions returns all active session IDs.
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	mustEmbedUnimplementedContextManagerServiceServer()
}

// UnimplementedContextManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContextManagerServiceServer struct{}

func (UnimplementedContextManagerServiceServer) NewSession(context.Context, *NewSessionRequest) (*NewSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NewSession not implemented")
}
func (UnimplementedContextManagerServiceServer) AddMessage(context.Context, *AddMessageRequest) (*AddMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMessage not implemented")
}
func (UnimplementedContextManagerServiceServer) GetMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMessages not implemented")
}
func (UnimplementedContextManagerServiceServer) GetSummary(context.Context, *GetSummaryRequest) (*GetSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSummary not implemented")
}
func (UnimplementedContextManagerServiceServer) BuildSystemPrompt(context.Context, *BuildSystemPromptRequest) (*BuildSystemPromptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BuildSystemPrompt not implemented")
}
func (UnimplementedContextManagerServiceServer) Clear(context.Context, *ContextClearRequest) (*ContextClearResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Clear not implemented")
}
func (UnimplementedContextManagerServiceServer) DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSession not implemented")
}
func (UnimplementedContextManagerServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedContextManagerServiceServer) mustEmbedUnimplementedContextManagerServiceServer() {}
func (UnimplementedContextManagerServiceServer) testEmbeddedByValue()                               {}

// UnsafeContextManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContextManagerServiceServer will
// result in compilation errors.
type UnsafeContextManagerServiceServer interface {
	mustEmbedUnimplementedContextManagerServiceServer()
}

func RegisterContextManagerServiceServer(s grpc.ServiceRegistrar, srv ContextManagerServiceServer) {
	// If the following call panics, it indicates UnimplementedContextManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContextManagerService_ServiceDesc, srv)
}

func _ContextManagerService_NewSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextManagerServiceServer).NewSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContextManagerService_NewSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextManagerServiceServer).NewSession(ctx, req.(*NewSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContextManagerService_AddMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextManagerServiceServer).AddMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContextManagerService_AddMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextManagerServiceServer).AddMessage(ctx, req.(*AddMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContextManagerService_GetMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextManagerServiceServer).GetMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContextManagerService_GetMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextManagerServiceServer).GetMessages(ctx, req.(*GetMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContextManagerService_GetSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextManagerServiceServer).GetSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContextManagerService_GetSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextManagerServiceServer).GetSummary(ctx, req.(*GetSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContextManagerService_BuildSystemPrompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildSystemPromptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextManagerServiceServer).BuildSystemPrompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContextManagerService_BuildSystemPrompt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextManagerServiceServer).BuildSystemPrompt(ctx, req.(*BuildSystemPromptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContextManagerService_Clear_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContextClearRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextManagerServiceServer).Clear(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContextManagerService_Clear_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextManagerServiceServer).Clear(ctx, req.(*ContextClearRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContextManagerService_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextManagerServiceServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContextManagerService_DeleteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextManagerServiceServer).DeleteSession(ctx, req.(*DeleteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContextManagerService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextManagerServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContextManagerService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextManagerServiceServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContextManagerService_ServiceDesc is the grpc.ServiceDesc for ContextManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContextManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gogent.v1.ContextManagerService",
	HandlerType: (*ContextManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewSession",
			Handler:    _ContextManagerService_NewSession_Handler,
		},
		{
			MethodName: "AddMessage",
			Handler:    _ContextManagerService_AddMessage_Handler,
		},
		{
			MethodName: "GetMessages",
			Handler:    _ContextManagerService_GetMessages_Handler,
		},
		{
			MethodName: "GetSummary",
			Handler:    _ContextManagerService_GetSummary_Handler,
		},
		{
			MethodName: "BuildSystemPrompt",
			Handler:    _ContextManagerService_BuildSystemPrompt_Handler,
		},
		{
			MethodName: "Clear",
			Handler:    _ContextManagerService_Clear_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _ContextManagerService_DeleteSession_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _ContextManagerService_ListSessions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contextmanager.proto",
}
