// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hook.proto

package gogentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HookEventType int32

const (
	HookEventType_HOOK_EVENT_TYPE_UNSPECIFIED HookEventType = 0
	HookEventType_HOOK_EVENT_TYPE_BEFORE_RUN  HookEventType = 1
	HookEventType_HOOK_EVENT_TYPE_AFTER_RUN   HookEventType = 2
	HookEventType_HOOK_EVENT_TYPE_BEFORE_TOOL HookEventType = 3
	HookEventType_HOOK_EVENT_TYPE_AFTER_TOOL  HookEventType = 4
	HookEventType_HOOK_EVENT_TYPE_BEFORE_LLM  HookEventType = 5
	HookEventType_HOOK_EVENT_TYPE_AFTER_LLM   HookEventType = 6
	HookEventType_HOOK_EVENT_TYPE_ERROR       HookEventType = 7
	HookEventType_HOOK_EVENT_TYPE_STREAMING   HookEventType = 8
)

// Enum value maps for HookEventType.
var (
	HookEventType_name = map[int32]string{
		0: "HOOK_EVENT_TYPE_UNSPECIFIED",
		1: "HOOK_EVENT_TYPE_BEFORE_RUN",
		2: "HOOK_EVENT_TYPE_AFTER_RUN",
		3: "HOOK_EVENT_TYPE_BEFORE_TOOL",
		4: "HOOK_EVENT_TYPE_AFTER_TOOL",
		5: "HOOK_EVENT_TYPE_BEFORE_LLM",
		6: "HOOK_EVENT_TYPE_AFTER_LLM",
		7: "HOOK_EVENT_TYPE_ERROR",
		8: "HOOK_EVENT_TYPE_STREAMING",
	}
	HookEventType_value = map[string]int32{
		"HOOK_EVENT_TYPE_UNSPECIFIED": 0,
		"HOOK_EVENT_TYPE_BEFORE_RUN":  1,
		"HOOK_EVENT_TYPE_AFTER_RUN":   2,
		"HOOK_EVENT_TYPE_BEFORE_TOOL": 3,
		"HOOK_EVENT_TYPE_AFTER_TOOL":  4,
		"HOOK_EVENT_TYPE_BEFORE_LLM":  5,
		"HOOK_EVENT_TYPE_AFTER_LLM":   6,
		"HOOK_EVENT_TYPE_ERROR":       7,
		"HOOK_EVENT_TYPE_STREAMING":   8,
	}
)

func (x HookEventType) Enum() *HookEventType {
	p := new(HookEventType)
	*p = x
	return p
}

func (x HookEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HookEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_hook_proto_enumTypes[0].Descriptor()
}

func (HookEventType) Type() protoreflect.EnumType {
	return &file_hook_proto_enumTypes[0]
}

func (x HookEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HookEventType.Descriptor instead.
func (HookEventType) EnumDescriptor() ([]byte, []int) {
	return file_hook_proto_rawDescGZIP(), []int{0}
}

type HookEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          HookEventType          `protobuf:"varint,1,opt,name=type,proto3,enum=gogent.v1.HookEventType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // hook.Event.Payload (any in Go)
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`     // hook.Event.Error serialized as string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookEventRequest) Reset() {
	*x = HookEventRequest{}
	mi := &file_hook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookEventRequest) ProtoMessage() {}

func (x *HookEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookEventRequest.ProtoReflect.Descriptor instead.
func (*HookEventRequest) Descriptor() ([]byte, []int) {
	return file_hook_proto_rawDescGZIP(), []int{0}
}

func (x *HookEventRequest) GetType() HookEventType {
	if x != nil {
		return x.Type
	}
	return HookEventType_HOOK_EVENT_TYPE_UNSPECIFIED
}

func (x *HookEventRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HookEventRequest) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *HookEventRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HookEventResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Context key-value pairs that the caller should merge into the
	// downstream context. Maps to the returned context.Context in Go.
	ContextValues map[string]string `protobuf:"bytes,1,rep,name=context_values,json=contextValues,proto3" json:"context_values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Non-nil error aborts the calling chain (maps to returned error).
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookEventResponse) Reset() {
	*x = HookEventResponse{}
	mi := &file_hook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookEventResponse) ProtoMessage() {}

func (x *HookEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookEventResponse.ProtoReflect.Descriptor instead.
func (*HookEventResponse) Descriptor() ([]byte, []int) {
	return file_hook_proto_rawDescGZIP(), []int{1}
}

func (x *HookEventResponse) GetContextValues() map[string]string {
	if x != nil {
		return x.ContextValues
	}
	return nil
}

func (x *HookEventResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_hook_proto protoreflect.FileDescriptor

const file_hook_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"hook.proto\x12\tgogent.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x9d\x01\n" +
	"\x10HookEventRequest\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.gogent.v1.HookEventTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x121\n" +
	"\apayload\x18\x03 \x01(\v2\x17.google.protobuf.StructR\apayload\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xc3\x01\n" +
	"\x11HookEventResponse\x12V\n" +
	"\x0econtext_values\x18\x01 \x03(\v2/.gogent.v1.HookEventResponse.ContextValuesEntryR\rcontextValues\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x1a@\n" +
	"\x12ContextValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xa9\x02\n" +
	"\rHookEventType\x12\x1f\n" +
	"\x1bHOOK_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aHOOK_EVENT_TYPE_BEFORE_RUN\x10\x01\x12\x1d\n" +
	"\x19HOOK_EVENT_TYPE_AFTER_RUN\x10\x02\x12\x1f\n" +
	"\x1bHOOK_EVENT_TYPE_BEFORE_TOOL\x10\x03\x12\x1e\n" +
	"\x1aHOOK_EVENT_TYPE_AFTER_TOOL\x10\x04\x12\x1e\n" +
	"\x1aHOOK_EVENT_TYPE_BEFORE_LLM\x10\x05\x12\x1d\n" +
	"\x19HOOK_EVENT_TYPE_AFTER_LLM\x10\x06\x12\x19\n" +
	"\x15HOOK_EVENT_TYPE_ERROR\x10\a\x12\x1d\n" +
	"\x19HOOK_EVENT_TYPE_STREAMING\x10\b2S\n" +
	"\vHookService\x12D\n" +
	"\aOnEvent\x12\x1b.gogent.v1.HookEventRequest\x1a\x1c.gogent.v1.HookEventResponseB\xa1\x01\n" +
	"\rcom.gogent.v1B\tHookProtoP\x01Z@github.com/tltre/gogent/internal/grpctransport/gogentv1;gogentv1\xa2\x02\x03GXX\xaa\x02\tGogent.V1\xca\x02\tGogent\\V1\xe2\x02\x15Gogent\\V1\\GPBMetadata\xea\x02\n" +
	"Gogent::V1b\x06proto3"

var (
	file_hook_proto_rawDescOnce sync.Once
	file_hook_proto_rawDescData []byte
)

func file_hook_proto_rawDescGZIP() []byte {
	file_hook_proto_rawDescOnce.Do(func() {
		file_hook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hook_proto_rawDesc), len(file_hook_proto_rawDesc)))
	})
	return file_hook_proto_rawDescData
}

var file_hook_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hook_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_hook_proto_goTypes = []any{
	(HookEventType)(0),        // 0: gogent.v1.HookEventType
	(*HookEventRequest)(nil),  // 1: gogent.v1.HookEventRequest
	(*HookEventResponse)(nil), // 2: gogent.v1.HookEventResponse
	nil,                       // 3: gogent.v1.HookEventResponse.ContextValuesEntry
	(*structpb.Struct)(nil),   // 4: google.protobuf.Struct
}
var file_hook_proto_depIdxs = []int32{
	0, // 0: gogent.v1.HookEventRequest.type:type_name -> gogent.v1.HookEventType
	4, // 1: gogent.v1.HookEventRequest.payload:type_name -> google.protobuf.Struct
	3, // 2: gogent.v1.HookEventResponse.context_values:type_name -> gogent.v1.HookEventResponse.ContextValuesEntry
	1, // 3: gogent.v1.HookService.OnEvent:input_type -> gogent.v1.HookEventRequest
	2, // 4: gogent.v1.HookService.OnEvent:output_type -> gogent.v1.HookEventResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_hook_proto_init() }
func file_hook_proto_init() {
	if File_hook_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hook_proto_rawDesc), len(file_hook_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hook_proto_goTypes,
		DependencyIndexes: file_hook_proto_depIdxs,
		EnumInfos:         file_hook_proto_enumTypes,
		MessageInfos:      file_hook_proto_msgTypes,
	}.Build()
	File_hook_proto = out.File
	file_hook_proto_goTypes = nil
	file_hook_proto_depIdxs = nil
}
