// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: memory.proto

package gogentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MemoryItem represents a single entry in the memory store.
type MemoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Extra         *structpb.Struct       `protobuf:"bytes,3,opt,name=extra,proto3" json:"extra,omitempty"`
	Embedding     []float64              `protobuf:"fixed64,4,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Score         float64                `protobuf:"fixed64,6,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryItem) Reset() {
	*x = MemoryItem{}
	mi := &file_memory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryItem) ProtoMessage() {}

func (x *MemoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryItem.ProtoReflect.Descriptor instead.
func (*MemoryItem) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{0}
}

func (x *MemoryItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MemoryItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MemoryItem) GetExtra() *structpb.Struct {
	if x != nil {
		return x.Extra
	}
	return nil
}

func (x *MemoryItem) GetEmbedding() []float64 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *MemoryItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MemoryItem) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

// MemoryQuery defines search parameters for memory retrieval.
type MemoryQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	TopK          int32                  `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Filter        *structpb.Struct       `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	MinScore      float64                `protobuf:"fixed64,4,opt,name=min_score,json=minScore,proto3" json:"min_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryQuery) Reset() {
	*x = MemoryQuery{}
	mi := &file_memory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryQuery) ProtoMessage() {}

func (x *MemoryQuery) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryQuery.ProtoReflect.Descriptor instead.
func (*MemoryQuery) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{1}
}

func (x *MemoryQuery) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MemoryQuery) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *MemoryQuery) GetFilter() *structpb.Struct {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *MemoryQuery) GetMinScore() float64 {
	if x != nil {
		return x.MinScore
	}
	return 0
}

// QueryRequest is the input to MemoryService.Query.
type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *MemoryQuery           `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_memory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{2}
}

func (x *QueryRequest) GetQuery() *MemoryQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

// QueryResponse is the output from MemoryService.Query.
type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MemoryItem          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_memory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{3}
}

func (x *QueryResponse) GetItems() []*MemoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// AddEntryRequest is the input to MemoryService.Add.
type AddEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *MemoryItem            `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEntryRequest) Reset() {
	*x = AddEntryRequest{}
	mi := &file_memory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEntryRequest) ProtoMessage() {}

func (x *AddEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEntryRequest.ProtoReflect.Descriptor instead.
func (*AddEntryRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{4}
}

func (x *AddEntryRequest) GetItem() *MemoryItem {
	if x != nil {
		return x.Item
	}
	return nil
}

// AddEntryResponse is the output from MemoryService.Add.
type AddEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEntryResponse) Reset() {
	*x = AddEntryResponse{}
	mi := &file_memory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEntryResponse) ProtoMessage() {}

func (x *AddEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEntryResponse.ProtoReflect.Descriptor instead.
func (*AddEntryResponse) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{5}
}

func (x *AddEntryResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// MemoryClearRequest is the input to MemoryService.Clear.
type MemoryClearRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryClearRequest) Reset() {
	*x = MemoryClearRequest{}
	mi := &file_memory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryClearRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryClearRequest) ProtoMessage() {}

func (x *MemoryClearRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryClearRequest.ProtoReflect.Descriptor instead.
func (*MemoryClearRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{6}
}

// MemoryClearResponse is the output from MemoryService.Clear.
type MemoryClearResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryClearResponse) Reset() {
	*x = MemoryClearResponse{}
	mi := &file_memory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryClearResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryClearResponse) ProtoMessage() {}

func (x *MemoryClearResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryClearResponse.ProtoReflect.Descriptor instead.
func (*MemoryClearResponse) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{7}
}

var File_memory_proto protoreflect.FileDescriptor

const file_memory_proto_rawDesc = "" +
	"\n" +
	"\fmemory.proto\x12\tgogent.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd4\x01\n" +
	"\n" +
	"MemoryItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12-\n" +
	"\x05extra\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x05extra\x12\x1c\n" +
	"\tembedding\x18\x04 \x03(\x01R\tembedding\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x14\n" +
	"\x05score\x18\x06 \x01(\x01R\x05score\"\x84\x01\n" +
	"\vMemoryQuery\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\x12/\n" +
	"\x06filter\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06filter\x12\x1b\n" +
	"\tmin_score\x18\x04 \x01(\x01R\bminScore\"<\n" +
	"\fQueryRequest\x12,\n" +
	"\x05query\x18\x01 \x01(\v2\x16.gogent.v1.MemoryQueryR\x05query\"<\n" +
	"\rQueryResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.gogent.v1.MemoryItemR\x05items\"<\n" +
	"\x0fAddEntryRequest\x12)\n" +
	"\x04item\x18\x01 \x01(\v2\x15.gogent.v1.MemoryItemR\x04item\"\"\n" +
	"\x10AddEntryResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12MemoryClearRequest\"\x15\n" +
	"\x13MemoryClearResponse2\xd3\x01\n" +
	"\rMemoryService\x12:\n" +
	"\x05Query\x12\x17.gogent.v1.QueryRequest\x1a\x18.gogent.v1.QueryResponse\x12>\n" +
	"\x03Add\x12\x1a.gogent.v1.AddEntryRequest\x1a\x1b.gogent.v1.AddEntryResponse\x12F\n" +
	"\x05Clear\x12\x1d.gogent.v1.MemoryClearRequest\x1a\x1e.gogent.v1.MemoryClearResponseB\xa3\x01\n" +
	"\rcom.gogent.v1B\vMemoryProtoP\x01Z@github.com/tltre/gogent/internal/grpctransport/gogentv1;gogentv1\xa2\x02\x03GXX\xaa\x02\tGogent.V1\xca\x02\tGogent\\V1\xe2\x02\x15Gogent\\V1\\GPBMetadata\xea\x02\n" +
	"Gogent::V1b\x06proto3"

var (
	file_memory_proto_rawDescOnce sync.Once
	file_memory_proto_rawDescData []byte
)

func file_memory_proto_rawDescGZIP() []byte {
	file_memory_proto_rawDescOnce.Do(func() {
		file_memory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_memory_proto_rawDesc), len(file_memory_proto_rawDesc)))
	})
	return file_memory_proto_rawDescData
}

var file_memory_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_memory_proto_goTypes = []any{
	(*MemoryItem)(nil),            // 0: gogent.v1.MemoryItem
	(*MemoryQuery)(nil),           // 1: gogent.v1.MemoryQuery
	(*QueryRequest)(nil),          // 2: gogent.v1.QueryRequest
	(*QueryResponse)(nil),         // 3: gogent.v1.QueryResponse
	(*AddEntryRequest)(nil),       // 4: gogent.v1.AddEntryRequest
	(*AddEntryResponse)(nil),      // 5: gogent.v1.AddEntryResponse
	(*MemoryClearRequest)(nil),    // 6: gogent.v1.MemoryClearRequest
	(*MemoryClearResponse)(nil),   // 7: gogent.v1.MemoryClearResponse
	(*structpb.Struct)(nil),       // 8: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_memory_proto_depIdxs = []int32{
	8, // 0: gogent.v1.MemoryItem.extra:type_name -> google.protobuf.Struct
	9, // 1: gogent.v1.MemoryItem.created_at:type_name -> google.protobuf.Timestamp
	8, // 2: gogent.v1.MemoryQuery.filter:type_name -> google.protobuf.Struct
	1, // 3: gogent.v1.QueryRequest.query:type_name -> gogent.v1.MemoryQuery
	0, // 4: gogent.v1.QueryResponse.items:type_name -> gogent.v1.MemoryItem
	0, // 5: gogent.v1.AddEntryRequest.item:type_name -> gogent.v1.MemoryItem
	2, // 6: gogent.v1.MemoryService.Query:input_type -> gogent.v1.QueryRequest
	4, // 7: gogent.v1.MemoryService.Add:input_type -> gogent.v1.AddEntryRequest
	6, // 8: gogent.v1.MemoryService.Clear:input_type -> gogent.v1.MemoryClearRequest
	3, // 9: gogent.v1.MemoryService.Query:output_type -> gogent.v1.QueryResponse
	5, // 10: gogent.v1.MemoryService.Add:output_type -> gogent.v1.AddEntryResponse
	7, // 11: gogent.v1.MemoryService.Clear:output_type -> gogent.v1.MemoryClearResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_memory_proto_init() }
func file_memory_proto_init() {
	if File_memory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_memory_proto_rawDesc), len(file_memory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_memory_proto_goTypes,
		DependencyIndexes: file_memory_proto_depIdxs,
		MessageInfos:      file_memory_proto_msgTypes,
	}.Build()
	File_memory_proto = out.File
	file_memory_proto_goTypes = nil
	file_memory_proto_depIdxs = nil
}
