// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: tool.proto

package gogentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ToolService_RegisterTool_FullMethodName     = "/gogent.v1.ToolService/RegisterTool"
	ToolService_UnregisterTool_FullMethodName   = "/gogent.v1.ToolService/UnregisterTool"
	ToolService_GetToolStatus_FullMethodName    = "/gogent.v1.ToolService/GetToolStatus"
	ToolService_ExecuteTool_FullMethodName      = "/gogent.v1.ToolService/ExecuteTool"
	ToolService_RegisterManifest_FullMethodName = "/gogent.v1.ToolService/RegisterManifest"
)

// ToolServiceClient is the client API for ToolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ToolServiceClient interface {
	// 工具定义管理 (v0.12.1)
	RegisterTool(ctx context.Context, in *RegisterToolRequest, opts ...grpc.CallOption) (*RegisterToolResponse, error)
	UnregisterTool(ctx context.Context, in *UnregisterToolRequest, opts ...grpc.CallOption) (*UnregisterToolResponse, error)
	GetToolStatus(ctx context.Context, in *GetToolStatusRequest, opts ...grpc.CallOption) (*GetToolStatusResponse, error)
	// 工具执行 - bidirectional streaming (v0.12.1)
	ExecuteTool(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ToolControl, ToolExecutionEvent], error)
	// Manifest 注册 (v0.12.3)
	RegisterManifest(ctx context.Context, in *ManifestRequest, opts ...grpc.CallOption) (*ManifestResponse, error)
}

type toolServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewToolServiceClient(cc grpc.ClientConnInterface) ToolServiceClient {
	return &toolServiceClient{cc}
}

func (c *toolServiceClient) RegisterTool(ctx context.Context, in *RegisterToolRequest, opts ...grpc.CallOption) (*RegisterToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterToolResponse)
	err := c.cc.Invoke(ctx, ToolService_RegisterTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) UnregisterTool(ctx context.Context, in *UnregisterToolRequest, opts ...grpc.CallOption) (*UnregisterToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterToolResponse)
	err := c.cc.Invoke(ctx, ToolService_UnregisterTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) GetToolStatus(ctx context.Context, in *GetToolStatusRequest, opts ...grpc.CallOption) (*GetToolStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetToolStatusResponse)
	err := c.cc.Invoke(ctx, ToolService_GetToolStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) ExecuteTool(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ToolControl, ToolExecutionEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ToolService_ServiceDesc.Streams[0], ToolService_ExecuteTool_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ToolControl, ToolExecutionEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ToolService_ExecuteToolClient = grpc.BidiStreamingClient[ToolControl, ToolExecutionEvent]

func (c *toolServiceClient) RegisterManifest(ctx context.Context, in *ManifestRequest, opts ...grpc.CallOption) (*ManifestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ManifestResponse)
	err := c.cc.Invoke(ctx, ToolService_RegisterManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToolServiceServer is the server API for ToolService service.
// All implementations must embed UnimplementedToolServiceServer
// for forward compatibility.
type ToolServiceServer interface {
	// 工具定义管理 (v0.12.1)
	RegisterTool(context.Context, *RegisterToolRequest) (*RegisterToolResponse, error)
	UnregisterTool(context.Context, *UnregisterToolRequest) (*UnregisterToolResponse, error)
	GetToolStatus(context.Context, *GetToolStatusRequest) (*GetToolStatusResponse, error)
	// 工具执行 - bidirectional streaming (v0.12.1)
	ExecuteTool(grpc.BidiStreamingServer[ToolControl, ToolExecutionEvent]) error
	// Manifest 注册 (v0.12.3)
	RegisterManifest(context.Context, *ManifestRequest) (*ManifestResponse, error)
	mustEmbedUnimplementedToolServiceServer()
}

// UnimplementedToolServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedToolServiceServer struct{}

func (UnimplementedToolServiceServer) RegisterTool(context.Context, *RegisterToolRequest) (*RegisterToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterTool not implemented")
}
func (UnimplementedToolServiceServer) UnregisterTool(context.Context, *UnregisterToolRequest) (*UnregisterToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnregisterTool not implemented")
}
func (UnimplementedToolServiceServer) GetToolStatus(context.Context, *GetToolStatusRequest) (*GetToolStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetToolStatus not implemented")
}
func (UnimplementedToolServiceServer) ExecuteTool(grpc.BidiStreamingServer[ToolControl, ToolExecutionEvent]) error {
	return status.Error(codes.Unimplemented, "method ExecuteTool not implemented")
}
func (UnimplementedToolServiceServer) RegisterManifest(context.Context, *ManifestRequest) (*ManifestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterManifest not implemented")
}
func (UnimplementedToolServiceServer) mustEmbedUnimplementedToolServiceServer() {}
func (UnimplementedToolServiceServer) testEmbeddedByValue()                     {}

// UnsafeToolServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ToolServiceServer will
// result in compilation errors.
type UnsafeToolServiceServer interface {
	mustEmbedUnimplementedToolServiceServer()
}

func RegisterToolServiceServer(s grpc.ServiceRegistrar, srv ToolServiceServer) {
	// If the following call panics, it indicates UnimplementedToolServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ToolService_ServiceDesc, srv)
}

func _ToolService_RegisterTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).RegisterTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_RegisterTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).RegisterTool(ctx, req.(*RegisterToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_UnregisterTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).UnregisterTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_UnregisterTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).UnregisterTool(ctx, req.(*UnregisterToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_GetToolStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetToolStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).GetToolStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_GetToolStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).GetToolStatus(ctx, req.(*GetToolStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_ExecuteTool_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ToolServiceServer).ExecuteTool(&grpc.GenericServerStream[ToolControl, ToolExecutionEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ToolService_ExecuteToolServer = grpc.BidiStreamingServer[ToolControl, ToolExecutionEvent]

func _ToolService_RegisterManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).RegisterManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_RegisterManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).RegisterManifest(ctx, req.(*ManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ToolService_ServiceDesc is the grpc.ServiceDesc for ToolService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ToolService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gogent.v1.ToolService",
	HandlerType: (*ToolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterTool",
			Handler:    _ToolService_RegisterTool_Handler,
		},
		{
			MethodName: "UnregisterTool",
			Handler:    _ToolService_UnregisterTool_Handler,
		},
		{
			MethodName: "GetToolStatus",
			Handler:    _ToolService_GetToolStatus_Handler,
		},
		{
			MethodName: "RegisterManifest",
			Handler:    _ToolService_RegisterManifest_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteTool",
			Handler:       _ToolService_ExecuteTool_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "tool.proto",
}
