// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tool.proto

package gogentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ToolInfo describes a registered tool exposed to agents.
type ToolInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Parameters    *structpb.Value        `protobuf:"bytes,3,opt,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolInfo) Reset() {
	*x = ToolInfo{}
	mi := &file_tool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolInfo) ProtoMessage() {}

func (x *ToolInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolInfo.ProtoReflect.Descriptor instead.
func (*ToolInfo) Descriptor() ([]byte, []int) {
	return file_tool_proto_rawDescGZIP(), []int{0}
}

func (x *ToolInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolInfo) GetParameters() *structpb.Value {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// ToolResult is the outcome of a tool execution.
type ToolResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        *structpb.Value        `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	IsError       bool                   `protobuf:"varint,2,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResult) Reset() {
	*x = ToolResult{}
	mi := &file_tool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResult) ProtoMessage() {}

func (x *ToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_tool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResult.ProtoReflect.Descriptor instead.
func (*ToolResult) Descriptor() ([]byte, []int) {
	return file_tool_proto_rawDescGZIP(), []int{1}
}

func (x *ToolResult) GetOutput() *structpb.Value {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ToolResult) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *ToolResult) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

// ListToolsRequest is the input to ToolService.ListTools.
type ListToolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsRequest) Reset() {
	*x = ListToolsRequest{}
	mi := &file_tool_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsRequest) ProtoMessage() {}

func (x *ListToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tool_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsRequest.ProtoReflect.Descriptor instead.
func (*ListToolsRequest) Descriptor() ([]byte, []int) {
	return file_tool_proto_rawDescGZIP(), []int{2}
}

// ListToolsResponse is the output from ToolService.ListTools.
type ListToolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tools         []*ToolInfo            `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsResponse) Reset() {
	*x = ListToolsResponse{}
	mi := &file_tool_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsResponse) ProtoMessage() {}

func (x *ListToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tool_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsResponse.ProtoReflect.Descriptor instead.
func (*ListToolsResponse) Descriptor() ([]byte, []int) {
	return file_tool_proto_rawDescGZIP(), []int{3}
}

func (x *ListToolsResponse) GetTools() []*ToolInfo {
	if x != nil {
		return x.Tools
	}
	return nil
}

// ExecuteToolRequest is the input to ToolService.ExecuteTool.
type ExecuteToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Params        *structpb.Struct       `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteToolRequest) Reset() {
	*x = ExecuteToolRequest{}
	mi := &file_tool_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteToolRequest) ProtoMessage() {}

func (x *ExecuteToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tool_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteToolRequest.ProtoReflect.Descriptor instead.
func (*ExecuteToolRequest) Descriptor() ([]byte, []int) {
	return file_tool_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteToolRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExecuteToolRequest) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

// ExecuteToolResponse is the output from ToolService.ExecuteTool.
type ExecuteToolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *ToolResult            `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteToolResponse) Reset() {
	*x = ExecuteToolResponse{}
	mi := &file_tool_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteToolResponse) ProtoMessage() {}

func (x *ExecuteToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tool_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteToolResponse.ProtoReflect.Descriptor instead.
func (*ExecuteToolResponse) Descriptor() ([]byte, []int) {
	return file_tool_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteToolResponse) GetResult() *ToolResult {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_tool_proto protoreflect.FileDescriptor

const file_tool_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"tool.proto\x12\tgogent.v1\x1a\x1cgoogle/protobuf/struct.proto\"x\n" +
	"\bToolInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x126\n" +
	"\n" +
	"parameters\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\n" +
	"parameters\"t\n" +
	"\n" +
	"ToolResult\x12.\n" +
	"\x06output\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\x06output\x12\x19\n" +
	"\bis_error\x18\x02 \x01(\bR\aisError\x12\x1b\n" +
	"\terror_msg\x18\x03 \x01(\tR\berrorMsg\"\x12\n" +
	"\x10ListToolsRequest\">\n" +
	"\x11ListToolsResponse\x12)\n" +
	"\x05tools\x18\x01 \x03(\v2\x13.gogent.v1.ToolInfoR\x05tools\"Y\n" +
	"\x12ExecuteToolRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12/\n" +
	"\x06params\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06params\"D\n" +
	"\x13ExecuteToolResponse\x12-\n" +
	"\x06result\x18\x01 \x01(\v2\x15.gogent.v1.ToolResultR\x06result2\xa3\x01\n" +
	"\vToolService\x12F\n" +
	"\tListTools\x12\x1b.gogent.v1.ListToolsRequest\x1a\x1c.gogent.v1.ListToolsResponse\x12L\n" +
	"\vExecuteTool\x12\x1d.gogent.v1.ExecuteToolRequest\x1a\x1e.gogent.v1.ExecuteToolResponseB\xa1\x01\n" +
	"\rcom.gogent.v1B\tToolProtoP\x01Z@github.com/tltre/gogent/internal/grpctransport/gogentv1;gogentv1\xa2\x02\x03GXX\xaa\x02\tGogent.V1\xca\x02\tGogent\\V1\xe2\x02\x15Gogent\\V1\\GPBMetadata\xea\x02\n" +
	"Gogent::V1b\x06proto3"

var (
	file_tool_proto_rawDescOnce sync.Once
	file_tool_proto_rawDescData []byte
)

func file_tool_proto_rawDescGZIP() []byte {
	file_tool_proto_rawDescOnce.Do(func() {
		file_tool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tool_proto_rawDesc), len(file_tool_proto_rawDesc)))
	})
	return file_tool_proto_rawDescData
}

var file_tool_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_tool_proto_goTypes = []any{
	(*ToolInfo)(nil),            // 0: gogent.v1.ToolInfo
	(*ToolResult)(nil),          // 1: gogent.v1.ToolResult
	(*ListToolsRequest)(nil),    // 2: gogent.v1.ListToolsRequest
	(*ListToolsResponse)(nil),   // 3: gogent.v1.ListToolsResponse
	(*ExecuteToolRequest)(nil),  // 4: gogent.v1.ExecuteToolRequest
	(*ExecuteToolResponse)(nil), // 5: gogent.v1.ExecuteToolResponse
	(*structpb.Value)(nil),      // 6: google.protobuf.Value
	(*structpb.Struct)(nil),     // 7: google.protobuf.Struct
}
var file_tool_proto_depIdxs = []int32{
	6, // 0: gogent.v1.ToolInfo.parameters:type_name -> google.protobuf.Value
	6, // 1: gogent.v1.ToolResult.output:type_name -> google.protobuf.Value
	0, // 2: gogent.v1.ListToolsResponse.tools:type_name -> gogent.v1.ToolInfo
	7, // 3: gogent.v1.ExecuteToolRequest.params:type_name -> google.protobuf.Struct
	1, // 4: gogent.v1.ExecuteToolResponse.result:type_name -> gogent.v1.ToolResult
	2, // 5: gogent.v1.ToolService.ListTools:input_type -> gogent.v1.ListToolsRequest
	4, // 6: gogent.v1.ToolService.ExecuteTool:input_type -> gogent.v1.ExecuteToolRequest
	3, // 7: gogent.v1.ToolService.ListTools:output_type -> gogent.v1.ListToolsResponse
	5, // 8: gogent.v1.ToolService.ExecuteTool:output_type -> gogent.v1.ExecuteToolResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_tool_proto_init() }
func file_tool_proto_init() {
	if File_tool_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tool_proto_rawDesc), len(file_tool_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tool_proto_goTypes,
		DependencyIndexes: file_tool_proto_depIdxs,
		MessageInfos:      file_tool_proto_msgTypes,
	}.Build()
	File_tool_proto = out.File
	file_tool_proto_goTypes = nil
	file_tool_proto_depIdxs = nil
}
